apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-component
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: jimarchitelli/prod-client
